/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sci-fi_coin.glb --transform 
Files: sci-fi_coin.glb [36.68KB] > /Users/liquidthought/www/html/animate/carousel/public/sci-fi_coin-transformed.glb [5.66KB] (85%)
Author: tomciomalina (https://sketchfab.com/tomciomalina)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-coin-e6c50859b7e841bc99b229f27f2e3fb9
Title: Sci-fi Coin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Coin(props) {
  const { nodes, materials } = useGLTF('/sci-fi_coin-transformed.glb')
  return (
    <group {...props} position={[0, 0, 0]} scale={[1]} dispose={null}>
      <mesh geometry={nodes['Tube004_Material_#161_Tube004_0'].geometry} material={materials.Material_161_Tube004} position={[1.686, 29.25, -0.01]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Tube004_14_-_Default_0'].geometry} material={materials['14_-_Default']} position={[1.686, 29.25, -0.01]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/sci-fi_coin-transformed.glb')
