/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 roulette.gltf --transform 
Files: roulette.gltf [43.6KB] > /Users/liquidthought/www/html/animate/carousel/public/roulette-transformed.glb [5.18KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Roulette(props) {
  const { nodes, materials } = useGLTF('/roulette-transformed.glb')
  return (
    <group {...props} ref={props.ref} scale={0.014} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Tube004_14_-_Default_0_1'].geometry} material={materials['14_-_Default']} />
        <mesh geometry={nodes['Tube004_14_-_Default_0_2'].geometry} material={materials.Material_161_Tube004} />
      </group>
    </group>
  )
}

useGLTF.preload('/roulette-transformed.glb')
